### ISSUE TITLE
False positive for domain name search

### ISSUE THREAD

**Issue by serdar** [toddcooke/namechecker#1]
Hello,
The domain search for sk.org was incorrectly flagged as available. When conducting the search on Google Domains there's an error (also incorrect on behalf of Google) stating that .org domains should be 3 characters, maybe that's messing up the search result?

Thanks

**Comment by devrudraa** [comment]
![image](https://github.com/toddcooke/namechecker/assets/75237456/6981851f-2aa3-4c3c-8365-e0e215521d25)

Cause this sk.rog is a invalid domain name as it says "Domains ending in .ORG must be between 3 and 63 characters"
@toddcooke should see that if the domain is invalid and give results according to that.

**Comment by theaswanson** [comment]
To add to this, I did a search for "google" and it said "google.ai" was available. However, it appears .ai domains are not available through Google Domains.

<img width="423" alt="image" src="https://github.com/toddcooke/namechecker/assets/25459801/ff59d69f-5ed1-4953-842c-71f8d5198b9f">
<img width="900" alt="image" src="https://github.com/toddcooke/namechecker/assets/25459801/b667b217-221c-490a-84c9-dd9fc7b1fdf2">

**Comment by toddcooke** [comment]
@devrudraa @theaswanson I switched the domain registrar links to namecheap which doesn't complain over short .org domains, and also because .ai domains are available from namecheap. Thanks both for pointing out these issues 👍

**Comment by serdar** [comment]
Thanks Todd!
