### ISSUE TITLE
Search links to Google domains no longer work

### ISSUE THREAD

**Issue by fienestar** [toddcooke/namechecker#11]
Google no longer offers new domain registrations.

```jsx
<li>
  <Link
    target={'_blank'}
    href={`https://domains.google.com/registrar/search?searchTerm=${text}&hl=en`}
  >
    ℹ️ Some domain names available
  </Link>
</li>
```

https://domains.google.com/registrar/search?searchTerm=some-example&hl=en

"Can't load your domains right now. Try again later."

**Comment by toddcooke** [comment]
Should be fixed now with a recent change, using namecheap rather than google domains.
Thanks for reporting this!
