### ISSUE TITLE
Application not up to date

### ISSUE THREAD

**Issue by PierrickP** [toddcooke/namechecker#15]
Hello, 
The current deployed application seem to be an old version.
I have a different result namechecker.vercel.app and current master commit

![image](https://github.com/toddcooke/namechecker/assets/1214544/fba64d0e-b7ea-497b-af9e-f69394dc2506)
![image](https://github.com/toddcooke/namechecker/assets/1214544/addb035d-d348-4821-97ba-c6db35a40dfd)

On hosted version
> Rust crate name is available!
this is wrong, https://crates.io/api/v1/crates/gbfs

**Comment by toddcooke** [comment]
Thanks for making the issue @PierrickP , I think the issue was that I wasn't passing the User-Agent header, which is required by the crates API. _Should_ be fixed now.

**Comment by PierrickP** [comment]
@toddcooke indeed, seams fixed !
That's strange, i tested locally, and didn't have the issue
