### ISSUE TITLE
npm organisations

### ISSUE THREAD

**Issue by simonkarman** [toddcooke/namechecker#68]
Awesome tool! I was looking at this for my npm package krmx.

Currently, the following url is returned: https://www.npmjs.com/package/krmx. However, that url gives a not found page. The following url is used to inspect the existance of the package: https://registry.npmjs.org/krmx (which does give a result) https://github.com/toddcooke/namechecker/blob/27f0236744b581f79e2f0b6cc4a0403f86ca989a/app/api/exists/npm/route.ts#L16

I'm not entirely sure if there actually used to be a package at `https://registry.npmjs.org/krmx` that is no longer listed. But it can be handy anyway to return wether the npm organisation is available.

The krmx npm organisation can be returned (too): https://www.npmjs.com/org/krmx

**Comment by toddcooke** [comment]
Thanks for the issue. I changed the registry url to be the api endpoint, and added support for npm orgs.
